// library/react/src/components/blocks/newsletter-form-01/index.tsx
/**
 * @component  newsletter-form-01
 * @name       Newsletter Form 01
 * @level      block
 * @usage      newsletter
 * @industries
 * @tags       minimal, form
 * @access     free
 * @source     https://buttondown.com
 * @deps
 * @version    1.0.0
 */
import type { ComponentPropsWithoutRef } from 'react';
import Button01 from '../../elements/button-01';
import Input01 from '../../elements/input-01';

interface NewsletterForm01Props extends ComponentPropsWithoutRef<'div'> {
    /** Input placeholder text. */
    placeholder?: string;
    /** Submit button label. */
    buttonLabel?: string;
    /** Privacy note under the form. Hidden when empty. */
    note?: string;
}

export default function NewsletterForm01({
    placeholder = 'you@example.com',
    buttonLabel = 'Subscribe',
    note = '',
    className = '',
    ...rest
}: NewsletterForm01Props) {
    return (
        <div {...rest} className={`flex w-full max-w-md flex-col gap-3 ${className}`}>
            <div className="flex flex-col gap-3 sm:flex-row">
                <div className="flex-1">
                    <Input01 placeholder={placeholder} />
                </div>
                <Button01 label={buttonLabel} href="#" className="shrink-0" />
            </div>
            {note !== '' && <p className="text-xs leading-5 text-neutral-500 dark:text-neutral-400">{note}</p>}
        </div>
    );
}

// library/vue/src/components/blocks/newsletter-form-01/index.vue
<script setup lang="ts">
/**
 * @component  newsletter-form-01
 * @name       Newsletter Form 01
 * @level      block
 * @usage      newsletter
 * @industries
 * @tags       minimal, form
 * @access     free
 * @source     https://buttondown.com
 * @deps
 * @version    1.0.0
 */
import Button01 from '../../elements/button-01/index.vue';
import Input01 from '../../elements/input-01/index.vue';

interface NewsletterForm01Props {
    /** Input placeholder text. */
    placeholder?: string;
    /** Submit button label. */
    buttonLabel?: string;
    /** Privacy note under the form. Hidden when empty. */
    note?: string;
}

const props = withDefaults(defineProps<NewsletterForm01Props>(), {
    placeholder: 'you@example.com',
    buttonLabel: 'Subscribe',
    note: '',
});
</script>

<template>
    <div class="flex w-full max-w-md flex-col gap-3">
        <div class="flex flex-col gap-3 sm:flex-row">
            <div class="flex-1">
                <Input01 :placeholder="props.placeholder" />
            </div>
            <Button01 :label="props.buttonLabel" href="#" class="shrink-0" />
        </div>
        <p v-if="props.note !== ''" class="text-xs leading-5 text-neutral-500 dark:text-neutral-400">{{ props.note }}</p>
    </div>
</template>
